/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kandavela' at '5/6/16 12:51 PM' with Gradle 2.6
 *
 * @author kandavela, @date 5/6/16 12:51 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
